### ISSUE TITLE
How to record all incoming mails to database tables?

### ISSUE THREAD

**Issue by varmad** [posty/posty_chef#2]
Hello,

I want to record all incoming mails to specific database how I can do this?

Please help me on this.

Thanks

**Comment by chicobico** [comment]
Why you want to record all incoming mails in the database?
The complete Mails?
I think its better to store it in a folder.

**Comment by varmad** [comment]
If we store in the database it's easy to process the bounces data.

**Comment by chicobico** [comment]
E-Mail Storage in Database is at the moment not supported by posty.
