### ISSUE TITLE
Add recipe to chef supermarket

### ISSUE THREAD

**Issue by alexanderadam** [posty/posty_chef#5]
Is there any reason why posty isn't added to the [supermarket](https://supermarket.chef.io/cookbooks) yet?

**Comment by lweis** [comment]
there is no reason why Posty is not listed in the supermarket, we have not yet established but it is equal to the Roadmap!
Thanks for the hint

**Comment by alexanderadam** [comment]
[What I wrote in issue 7](https://github.com/posty/posty_chef/issues/7#issuecomment-174916941) also applies here of course.

Were is the mentioned roadmap? It seems not to be in the git repo nor are you using github issues.
In open source software it would be much easier for contributors to have a roadmap / open issues accessible for everyone.

**EDIT**: I found the, or at least a, [roadmap](https://posty-soft.org/roadmap.pdf) but it isn't listed there. :wink: 
**EDIT 2**: Okay, I guess then it is the, at least for me, inacessible [JIRA-instance](https://postysoft.atlassian.net/browse/CHEF)? If it is, it really isn't optimal for open source software.
